ekf_filter_node:
  ros__parameters:
    # use_sim_time: true
    frequency: 60.0
    two_d_mode: true
    publish_tf: true

    map_frame: odom
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_remove_gravitational_acceleration: true

    odom0: /odom
    odom0_config: [false, false, false, # x, y, z
                  false, false, false, # roll, pitch, yaw
                  true, true, false, # vx, vy, vz
                  true, true, false, # vroll, vpitch, vyaw
                  false, false, false] # ax, ay, az
